# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_field',
            field=models.EmailField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
