# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_email_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email_field2',
            field=models.EmailField(default='default@gmail.com', max_length=250),
            preserve_default=False,
        ),
    ]
